name: SAM Validate

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Install AWS CLI and SAM CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Download SAM CLI
      run: |
        curl -Lo /tmp/sam.zip https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
        sudo unzip /tmp/sam.zip -d /usr/local/bin/

    - name: Install SAM CLI
      run: |
        sudo ln -s /usr/local/bin/aws-sam-cli-*/usr/local/bin/sam

    - name: Verify SAM CLI Installation
      run: sam --version

    - name: Validate SAM template
      run: |
        sam validate --template template.yaml
