name: FC-Backend-deployment

on:
  push:
    branches:
      - dev  # Replace with your branch name

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::478313837588:role/github-actions-role
        aws-region: us-east-2

 #   - name: Install AWS CLI and SAM CLI
 #     run: |
 #       sudo apt-get update
 #       sudo apt-get install -y awscli

#    - name: Download SAM CLI
#      run: |
#        curl -Lo /tmp/sam.zip https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
#        sudo unzip /tmp/sam.zip -d /usr/local/bin/
#
#    - name: Install SAM CLI
#      run: |
#        sudo ln -s /usr/local/bin/aws-sam-cli-*/usr/local/bin/sam
#
    - name: Verify SAM CLI Installation
      run: sam --version

    - name: Validate SAM template
      run: |
        sam validate --template template.yaml
    
    - name: Install Python dependencies essential layer
      run: |
        cd layers/fileops-essentials-layer/python
        pip install -r requirements.txt -t .
    - name: Install Python dependencies for jinja2 layer
      run: |
        cd layers/fileops-jinja2-layer/python
        pip install -r requirements.txt -t . 
 
    - name: Deploy SAM template
      run: |
        sam deploy --template-file template.yaml --stack-name fileops-stack-qaa --no-confirm-changeset --parameter-overrides Environment=qaa
