name: SAM Validate

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Install AWS CLI and SAM CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli
        sudo apt-get install -y unzip
        curl -Lo sam.zip https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
        unzip sam.zip -d sam-installation
        sudo ./sam-installation/install
        sam --version

    - name: Validate SAM template
      run: |
        sam validate --template template.yaml
